// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.glartek.glarassist",
    "name": "GlarAssist",
    "description": "This is a Mattermost plugin for the Glartek Remote Assistance.",
    "version": "0.1.4",
    "min_server_version": "5.12.0",
    "server": {
        "executables": {
            "linux-amd64": "server/dist/plugin-linux-amd64"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": [
            {
                "key": "SERVER_URL",
                "display_name": "GlarAssist Server URL",
                "type": "text",
                "help_text": "Enter the URL of the GlarAssist server.",
                "placeholder": "",
                "default": "https://app.glarassist.com"
            },
            {
                "key": "API_SECRET",
                "display_name": "Secret",
                "type": "text",
                "help_text": "The secret to connect to the GlarAssist.",
                "placeholder": "",
                "default": ""
            }
        ]
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
